language: python
python:
  - "3.6"
matrix:
  include:

  # default Python + latest Sphinx + check for broken links
  - env: ADDITIONAL_COMMAND="python -m sphinx doc/ doc/_build/ -b linkcheck"

  # a few older Sphinx releases using default Python version
  - env: SPHINX="==1.3.2"
  - env: SPHINX="==1.3.6"
  - env: SPHINX="==1.4.9"
  - env: SPHINX="==1.5.1"
  - env: SPHINX="==1.5.3"
  - env: SPHINX="==1.5.6"

  # a few Python versions using latest Sphinx release
  - python: "3.4"
  - python: "3.5"
  - python: "nightly"
  - python: "pypy3"

addons:
  apt:
    packages:
      - pandoc
install:
  - pip install Sphinx$SPHINX
  - pip install .
  - pip install -r doc/requirements.txt
script:
  - python -m sphinx doc/ doc/_build/ -b html
  - python -m sphinx doc/ doc/_build/ -b latex
  - $ADDITIONAL_COMMAND
