language: python
python:
  - "3.6"
matrix:
  include:

  # default Python + latest Sphinx + check for broken links
  - env: ADDITIONAL_COMMAND="python -m sphinx doc/ doc/_build/ -b linkcheck"

  # a few older Sphinx releases using default Python version
  - env: SPHINX="==1.6.2"
  - env: SPHINX="==1.6.7"
  - env: SPHINX="==1.7.5"
  - env: SPHINX="==1.8.2"

  # a few Python versions using latest Sphinx release
  - python: "3.4"
  - python: "3.5"
  - python: "nightly"
  - python: "pypy3"

addons:
  apt:
    packages:
      - pandoc
install:
  - pip install Sphinx$SPHINX
  - pip install .
  - pip install ipykernel
  - pip install matplotlib
  - pip install sphinxcontrib-bibtex
script:
  - python -m sphinx doc/ doc/_build/ -b html
  - python -m sphinx doc/ doc/_build/ -b latex
  - python -m sphinx doc/ doc/_build/ -b epub
  - $ADDITIONAL_COMMAND
